name: geo
channels:
  - conda-forge
dependencies:
  - cartopy
  - contextily
  - folium
  - gdal
  - geopandas
  - geoplot
  - geopy
  - geoviews
  - hvplot
  - jupyterlab
  - matplotlib
  - mplleaflet
  - networkx
  - nodejs
  - numpy
  - osmnx
  - pandas
  - plotly
  - pyppeteer
  - pyproj
  - pysal
  - python
  - rasterio
  - rasterstats
  - richdem
  - scipy
  - seaborn
  - shapely
  - stateplane
  - utm
