name: mirror-content

on:
  push:
    branches:
      - main

jobs:

  mirror-to-binder-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get-date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - uses: olivr/copybara-action@v1.2.3
        with:
          access_token: ${{ github.token }}
          ssh_key: ${{ secrets.SSH_KEY }}
          sot_repo: ${{ github.repository }}
          sot_branch: main
          destination_repo: ${{ github.repository }}
          destination_branch: binder
          push_include: |
            binder/**
            tutorial/**
          push_replace: |
            GH-ACTIONS-DATE||${{ env.date }}||**.ipynb
          push_move: |
            binder||.binder
            tutorial||
          workflow: push

  mirror-to-tutorial-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get-date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - uses: olivr/copybara-action@v1.2.3
        with:
          access_token: ${{ github.token }}
          ssh_key: ${{ secrets.SSH_KEY }}
          sot_repo: ${{ github.repository }}
          sot_branch: main
          destination_repo: ${{ github.repository }}
          destination_branch: tutorial
          push_include: |
            binder/environment.yml
            tutorial/**
          push_replace: |
            GH-ACTIONS-DATE||${{ env.date }}||**.ipynb
          push_move: |
            binder/environment.yml||environment.yml
            tutorial||
          workflow: push
